### ISSUE TITLE
chore: Create new slack channel for cooking pictures

### ISSUE THREAD

**Issue by apoorvasheera** [uwescience/DSSG2024-cookbook#29]
Apoorva and Daniel to create a new slack channel called cooking-pictures and add all members of the GitHub. There is an urgent need for sharing of operationalized recipes to prevent catfishing from YouTube videos.

**Comment by voglerdaniel** [comment]
🫡 🫡 🫡 🫡

**Comment by apoorvasheera** [comment]
I think the name should be food related

**Comment by atkissoncj** [comment]
I wonder if even for chore issues, should we ask additional reviewers to do the actual closing? Might do it with an @ mention, like @apoorvasheera and @voglerdaniel . Just an idea...
